# Generated by Django 5.2.1 on 2025-05-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Дизайнер',
                'verbose_name_plural': 'Дизайнеры',
            },
        ),
        migrations.CreateModel(
            name='MafStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='MafType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
            ],
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='maf',
            options={'verbose_name': 'МАФ', 'verbose_name_plural': 'МАФы'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maf',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maf',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='house',
            name='duration',
            field=models.CharField(default=1, max_length=100, verbose_name='Время постройки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='living_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Жилая площадь (м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Общая площадь (м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maf',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Диаметр (см)'),
        ),
        migrations.AddField(
            model_name='maf',
            name='duration',
            field=models.CharField(default=1, max_length=100, verbose_name='Время постройки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maf',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='maf',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='maf',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AddField(
            model_name='house',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.designer'),
        ),
        migrations.AddField(
            model_name='maf',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.designer'),
        ),
        migrations.AddField(
            model_name='maf',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mafstyle', verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='maf',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.maftype', verbose_name='Тип'),
        ),
    ]
