# Generated by Django 5.2.1 on 2025-05-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_designer_mafstyle_maftype_alter_house_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mafstyle',
            options={'verbose_name': 'Стиль МАФа', 'verbose_name_plural': 'Стили МАФов'},
        ),
        migrations.AlterModelOptions(
            name='maftype',
            options={'verbose_name': 'Тип МАФа', 'verbose_name_plural': 'Типы МАФов'},
        ),
        migrations.AlterField(
            model_name='house',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.designer', verbose_name='Дизайнер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maf',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.designer', verbose_name='Дизайнер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maf',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.mafstyle', verbose_name='Стиль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maf',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.maftype', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mafstyle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maftype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
