# Generated by Django 5.2.1 on 2025-06-03 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_mafstyle_options_alter_maftype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='duration',
            field=models.CharField(max_length=30, verbose_name='Время постройки'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, ₽'),
        ),
        migrations.AlterField(
            model_name='house',
            name='stl_file',
            field=models.FileField(upload_to='stl_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='Файл STL'),
        ),
        migrations.AlterField(
            model_name='maf',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, ₽'),
        ),
        migrations.AlterField(
            model_name='maf',
            name='stl_file',
            field=models.FileField(upload_to='stl_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='Файл STL'),
        ),
    ]
