# Generated by Django 5.2.1 on 2025-06-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_house_duration_alter_house_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон или Email')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.application')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.house')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='houses',
            field=models.ManyToManyField(through='catalog.ApplicationHouse', to='catalog.house'),
        ),
        migrations.CreateModel(
            name='ApplicationMaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.application')),
                ('maf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.maf')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='mafs',
            field=models.ManyToManyField(through='catalog.ApplicationMaf', to='catalog.maf'),
        ),
    ]
