# Generated by Django 5.2.1 on 2025-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_application_applicationhouse_application_houses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationhouse',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='applicationmaf',
            options={'verbose_name': 'МАФ', 'verbose_name_plural': 'МАФы'},
        ),
        migrations.AlterField(
            model_name='applicationhouse',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='applicationmaf',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
