# Generated by Django 5.2.1 on 2025-07-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MafImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, verbose_name='Google Drive File ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.maf')),
            ],
            options={
                'verbose_name': 'Изображение МАФа',
                'verbose_name_plural': 'Изображения МАФов',
            },
        ),
    ]
