# Generated by Django 5.2.1 on 2025-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_mafimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafimage',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
    ]
