# Generated by Django 5.2.1 on 2025-07-07 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_mafimage_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stl_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='Файл STL'),
        ),
        migrations.CreateModel(
            name='HouseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, verbose_name='Google Drive File ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.house')),
            ],
            options={
                'verbose_name': 'Файл дома',
                'verbose_name_plural': 'Файлы домов',
            },
        ),
    ]
