# Generated by Django 5.2.1 on 2025-07-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_house_stl_file_housefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Leave blank to auto-fill from Google Drive file name.', max_length=255, verbose_name='Original Filename'),
        ),
    ]
