# Generated by Django 5.2.1 on 2025-07-08 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_housefile_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mafimage',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='mafimage',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='mafimage',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='mafimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='mafimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maf_images/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='MafFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, verbose_name='Google Drive File ID')),
                ('original_filename', models.CharField(blank=True, help_text='Leave blank to auto-fill from Google Drive file name.', max_length=255, verbose_name='Original Filename')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.maf')),
            ],
            options={
                'verbose_name': 'Файл МАФа',
                'verbose_name_plural': 'Файлы МАФов',
            },
        ),
    ]
