# Generated by Django 5.2.1 on 2025-07-08 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_mafimage_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maf',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stl_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='Файл STL'),
        ),
    ]
