# Generated by Django 5.2.1 on 2025-07-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_maf_stl_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefile',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='maffile',
            name='drive_file_id',
        ),
        migrations.AddField(
            model_name='housefile',
            name='yandex_disk_link',
            field=models.URLField(blank=True, help_text='Paste Yandex Disk public sharing link here', max_length=512, null=True, verbose_name='Yandex Disk Public Link'),
        ),
        migrations.AddField(
            model_name='maffile',
            name='yandex_disk_link',
            field=models.URLField(blank=True, help_text='Paste Yandex Disk public sharing link here', max_length=512, null=True, verbose_name='Yandex Disk Public Link'),
        ),
        migrations.AlterField(
            model_name='housefile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Leave blank to auto-fill from Yandex Disk if possible.', max_length=255, verbose_name='Original Filename'),
        ),
        migrations.AlterField(
            model_name='maffile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Leave blank to auto-fill from Yandex Disk if possible.', max_length=255, verbose_name='Original Filename'),
        ),
    ]
