# Generated by Django 5.2.1 on 2025-08-09 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_housefile_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='house',
            name='stl_coordinates',
            field=models.JSONField(blank=True, help_text='Пример: {"x": 0, "y": 0, "z": 0, "rotation": [0,0,0], "scale": 1.0}', null=True, verbose_name='Координаты STL модели'),
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='maf',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='maf',
            name='stl_coordinates',
            field=models.JSONField(blank=True, help_text='Пример: {"x": 0, "y": 0, "z": 0, "rotation": [0,0,0], "scale": 1.0}', null=True, verbose_name='Координаты STL модели'),
        ),
        migrations.AddField(
            model_name='maf',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
