# Generated by Django 5.2.1 on 2025-09-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_house_created_at_alter_house_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='stl_coordinates',
            field=models.JSONField(blank=True, help_text='Пример: {"cameraPosition": [0, 0, 150], "target": [0, 0, 0]}', null=True, verbose_name='Координаты и направление камеры по умолчанию.'),
        ),
        migrations.AlterField(
            model_name='maf',
            name='stl_coordinates',
            field=models.JSONField(blank=True, help_text='Пример: {"cameraPosition": [0, 0, 150], "target": [0, 0, 0]}', null=True, verbose_name='Координаты и направление камеры по умолчанию.'),
        ),
    ]
